{% set name = "ebg" %}
{% set version = "0.13.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 7a423bdd6401f342ebeea930a2cb8f707e3b14c79bfb360c5d81538564098199

build:
  number: 0
  noarch: python
  entry_points:
    - ebg = EBG.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - biopython
    - ete3
    - lightgbm
    - networkx
    - numpy
    - pandas
    - python >=3.6
    - scipy

test:
  imports:
    - EBG
    - EBG.Features
    - EBG.Models
    - EBG.Prediction
    - EBG.utils
  commands:
    - ebg --help

about:
  home: https://github.com/wiegertj/EBG
  summary: 'EBG is a fast predictor for the standard non-parametric Felsenstein Bootstrap support (SBS)'
  description: 'EBG is a fast predictor for the standard non-parametric Felsenstein Bootstrap support (SBS) of phylogenetic trees in python. It uses RAxML-NG phylogenies as input and predicts the SBS values of all non-trivial branches.'
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/wiegertj/EBG/wiki
  dev_url: https://github.com/wiegertj/EBG

extra:
  recipe-maintainers:
    - wiegertj
